sudo: required
dist: trusty
language: node_js

node_js:
  - "node"

services:
  - docker

  - 
  - 
  
install: 
  - make init

script:
  - export SNAP_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$SNAP_BRANCH"
  - make test
  - make build
  - make docker_build
  - make docker_test

deploy:
  provider: script
  skip_cleanup: true
  script: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS && make docker_push
  on:
    branch: master
