sudo: required
dist: trusty
language: node_js

node_js:
  - "node"
  
services:
  - docker

install: 
  - make init

script: 
  - make test
  - make build
  - make docker_build
  - make docker_test

deploy:
  provider: script
  script: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS && make docker_push
  on:
    branch: master
